version: "3"
services:
  db:
    container_name: notes_db
    image: postgres
    environment:
      - POSTGRES_DB=note_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev12345
      - POSTGRES_DATABASE=note_app
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    networks:
      - note-app
    volumes:
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: pg_isready -U postgres

  frontend:
    container_name: notes_frontend
    image: frontend
    environment:
      - REACT_APP_BACKEND=http://localhost:3001
      - REACT_APP_DOMAIN=${REACT_APP_DOMAIN}
      - REACT_APP_CLIENTID=${REACT_APP_CLIENTID}
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - note-app
    volumes:
      - ./client:/src:ro
      - /src/node_modules
    depends_on:
      - backend

  backend:
    container_name: notes_backend
    image: backend
    environment:
      - POSTGRES_URL=postgres://postgres:dev12345@notes_db:5432/note_app
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3001"
    networks:
      - note-app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/src
      - /src/node_modules



networks:
  note-app:
    driver: bridge
volumes:
  postgres:
    driver: local