version: "3"
services:
  frontend:
    image: frontend
    environment:
     - REACT_APP_BACKEND=http://localhost:3001
     - REACT_APP_DOMAIN=${REACT_APP_DOMAIN}
     - REACT_APP_CLIENTID=${REACT_APP_CLIENTID}
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - note-app
  backend:
    image: backend
    environment:
      - POSTGRES_URL=postgres://postgres:dev12345@db:5432/note_app
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - note-app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB="note_app"
      - PGUSER=postgres
      - PGPASSWORD=dev12345
      - PGDATABASE=note_app
      - PGPORT=5432

    ports:
      - "5432:5432"
    networks:
      - note-app
    volumes:
      - ./note-taking-app-backend/postgresql/data:/var/lib/postgresql/data
networks:
  note-app:
    driver: bridge
volumes:
  postgres:
    driver: local