version: "3"
services:
  frontend:
    env_file: note-taking-app-frontend/.env
    image: frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - note-app
  backend:
    # env_file: note-taking-app-backend/.env
    image: backend
    environment:
      - REACT_APP_BACKEND=http://localhost:3001
      - REACT_APP_DOMAIN=dev-idli2clb.us.auth0.com
      - REACT_APP_CLIENTID=66yR74o1o84Sbs2T3tSuVCPjiUI3nRHU
    ports:
      - "3001:3001"
    networks:
      - note-app
    depends_on:
      - db
  db:
    image: postgres
    # env_file: note-taking-app-backend/.env
    environment:
      - POSTGRES_DB="note_app"
      - PORT=3001
      - PGUSER=postgres
      - PGPASSWORD=dev12345
      - PGDATABASE=note_app
      - PGPORT=5432
      - POSTGRES_URL=postgres://postgres:dev12345@db:5432/note_app
    ports:
      - "5432:5432"
    networks:
      - note-app
    volumes:
      - ./note-taking-app-backend/postgresql/data:/var/lib/postgresql/data
networks:
  note-app:
    driver: bridge
volumes:
  postgres:
    driver: local


# version: '3'

# services:

#   backend:
#     env_file: .env
#     container_name: backend
#     build: .
#     volumes:
#     - '.:/src'
#     ports:
#     - 3001:3001
#     command: npm start

#   db:
#     image: postgres
#     ports: 
#     - 5432:5432
#     env_file: .env
#     volumes:
#     - ./postgresql/data:/var/lib/postgresql/data