version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=note_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev12345
      - POSTGRES_DATABASE=note_app
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    networks:
      - note-app
    volumes:
      # - ./note-taking-app-backend/postgresql/data:/var/lib/postgresql/data
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: pg_isready -U postgres

  frontend:
    image: frontend
    environment:
      - REACT_APP_BACKEND=http://localhost:3001
      - REACT_APP_DOMAIN=${REACT_APP_DOMAIN}
      - REACT_APP_CLIENTID=${REACT_APP_CLIENTID}
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - note-app
    volumes:
      - ./note-taking-app-frontend:/src:ro
      - /src/node_modules

  backend:
    image: backend
    environment:
      - POSTGRES_URL=postgres://postgres:dev12345@note-taking-app-db-1:5432/note_app
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3001"
    networks:
      - note-app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./note-taking-app-backend:/src
      - /src/node_modules



networks:
  note-app:
    driver: bridge
volumes:
  postgres:
    driver: local