version: "3"
services:
  frontend:
    env_file: note-taking-app-frontend/.env
    image: frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - note-app
  backend:
    env_file: note-taking-app-backend/.env
    image: backend
    ports:
      - "3001:3001"
    networks:
      - note-app
    depends_on:
      - db
  db:
    image: postgres
    env_file: note-taking-app-backend/.env
    environment:
      - POSTGRES_DB="note_app"
    ports:
      - "5432:5432"
    networks:
      - note-app
    volumes:
      - ./note-taking-app-backend/postgresql/data:/var/lib/postgresql/data
networks:
  note-app:
    driver: bridge
volumes:
  postgres:
    driver: local


# version: '3'

# services:

#   backend:
#     env_file: .env
#     container_name: backend
#     build: .
#     volumes:
#     - '.:/src'
#     ports:
#     - 3001:3001
#     command: npm start

#   db:
#     image: postgres
#     ports: 
#     - 5432:5432
#     env_file: .env
#     volumes:
#     - ./postgresql/data:/var/lib/postgresql/data